"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_ES_NAME = 'es';
exports.LANG_ES_TRANS = {
    'PROYECTO': 'Proyecto Carretillas',
    'ATENTICADO': "Has autenticado como ",
    'NO_VIDEOS': 'No existen videos con esos parámetros.',
    'SALIR': "Salir ",
    'CAPTURA': "Captura de pantalla del video",
    'DESCARGA': "Descargar en escritorio: ",
    'DESCARGA2': "Descarga",
    'EMAIL_ENTER': "Introduce el email: ",
    'PWD_ENTER': "Introduce la contraseña",
    'ACCEDE': "Accede",
    'VIDEO_PEDIDO': 'Video pedido',
    'PULSA_IZQ': 'Pulsa para ir a la izquierda',
    'PULSA_DER': 'Pulsa para ir a la derecha',
    'FRAME_BACK': 'Pulsa para ir a un frame anterior',
    'FRAME_POST': 'Pulsa para ir a un frame posterior',
    'VELOCIDAD': 'Velocidad',
    'FOTO': 'Toma una foto del video',
    'CROP': 'Recorta el video',
    'HORA_INICIO': 'Hora de inicio',
    'HORA_FIN': 'Hora de fin',
    'CLIENTE': 'Cliente',
    'PEDIDO': 'Pedido',
    'CARRETILLA': 'Carretilla',
    'NSERIE': 'Numero de serie',
    'BUSCA': 'Buscar videos',
    'LIVE_CAMERAS': 'Camaras en directo',
    'FECHA': 'Fecha',
    'SEL_L_PEDIDO': 'Selecciona una linea de pedido',
    'L_PEDIDO': 'Linea de pedido',
    'ES': 'Español',
    'EN': 'Inglés',
    'CAT': 'Catalán',
    'ACCESS_VIDEO': 'Clica para acceder al video',
    'VOLVER_VIDEO': 'Volver al video completo',
    'video_completo': 'Video completo',
    'linea_pedido': 'Linea de pedido',
    'INICIO': 'Inicio: ',
    'HORA': 'hora: ',
    'PULSACION': 'Pulsación: ',
    'FINAL': 'Final de ',
    'Y_PULS': ' y pulsación',
    'BAD_LOG': 'Credenciales erroneos',
    'SEL_LENG': 'Selecciona una lengua',
    'AUT_PB': 'Autentícate para acceder a la plataforma',
    'GESTION': 'Gestión',
    'ADMINISTRACION': 'Administración'
};
