export const LANG_CAT_NAME = 'cat';

export const LANG_CAT_TRANS = {
      "PROYECTO": "Projecte Carretons",
      "ATENTICADO": "T'has authenticat com a ",
      "SALIR": "Eixir ",
      'NO_VIDEOS' : 'No n\'hi ha vídeos amb els paràmetres cercats',
      "CAPTURA": "Captura de la pantalla del vídeo",
      "DESCARGA": "Descarrega a l'escriptori",
      "DESCARGA2": "Descarrega",
      "EMAIL_ENTER": "Introduix el teu nom d'usuari: ",
      "PWD_ENTER": "Introduix la contrasenya: ",
      "ACCEDE": "Accedix",
      'VIDEO_PEDIDO': 'Vídeo comanda',
      'PULSA_IZQ': 'Pulsa per anar a l\'esquerra',
      'PULSA_DER': 'Pulsa per anar a la dreta',
      'FRAME_BACK': 'Pulsa per anar un frame anterior',
      'FRAME_POST': 'Pulsa per anar un frame posterior',
      'VELOCIDAD': 'Velocitat',
      'FOTO': 'Pren una foto del vídeo',
      'CROP': 'Retalla el vídeo',
      'HORA_INICIO': 'Hora d\'inici',
      'HORA_FIN': 'Hora de final',
      'CLIENTE': 'Client',
      'PEDIDO': 'Comanda',
      'CARRETILLA': 'Carretó',
      'NSERIE': 'Nombre de sèrie',
      'BUSCA': 'Cerca vídeos',
      'LIVE_CAMERAS': 'Càmeres en directe',
      'FECHA': 'Data',
      'SEL_L_PEDIDO': 'Selecciona una línea de comanda',
      'L_PEDIDO': 'Línea de comanda',
      'ES': 'Espanyol',
      'EN': 'Anglès',
      'CAT': 'Català',
      'ACCESS_VIDEO': 'Clicka per accedir el vídeo',
      'VOLVER_VIDEO': 'Tornar al vídeo sencer',
      'video_completo': 'Vídeo sencer',
      'linea_pedido': 'Línea de comanda',
      'INICIO': 'Inici: ',
      'HORA': 'hora ',
      'PULSACION': 'Pulsació ',
      'FINAL': 'Final de ',
      'Y_PULS': ' i pulsació',
      'BAD_LOG': 'Credencials erronis',
      'SEL_LENG': 'Selecciona una llengua',
      'AUT_PB': 'Autentica\'t per accedir el web',
      'GESTION': 'Gestió',
      'ADMINISTRACION': 'Administració',
      'PWD_CH_OPT': 'Canvia la contrasenya',
      'INTRO_PWD': 'Introduix una contrasenya de minim 8 digits, amb almenys una minuscula, una majuscula i un digit',
      'INTRO_NEW_PWD': 'Introduix la nova contrasenya',
      'INTRO_OLD_PWD': 'Introduix la contrasenya actual',
      'CHANGE_PWD': 'Canviar contrasenya',
      'OLD_PWD_REQ': 'Es requerix la contrasenya actual',
      'NEW_PWD_REQ': 'Es requerix la contrasenya nova',
      'YES': 'Sí',
      'USERNAME': 'Nom d\'usuari',
      'ENT_VALID_PWD': 'Introduix una contrasenya vàlida',
      'SEG_CH_PWD': 'De segur que vols canviar-te la contrasenya?',
      'ALTA_USERS': 'Enregistrar usuaris',
      'CLIENT': 'Client',
      'W_USER': 'Usuari treballador',
      'INTRO_VALID_EM': 'Introduix un email vàlid',
      'EM_REQ': 'El email es requerix',
      'DAR_ALTA': 'Donar d\'alta',
      'ADMIN_USERS': 'Administrar usuaris',
      'VISUALIZE': 'Visualitzar',
      'DEL_USER': 'Borrar usuari',
      'SEG_DEL_USER': 'De segur que vols borrar eixe usuari?',
      'BUSC_USER': 'Cercar usuari',
      'SEG_ALTA_USER': 'De segur que vols donar d\'alta aquest usuari?',
      'DESC_VIDEO': 'Descarregar vídeo',
      'ERR_SYS_LOG': 'Ha hagut un problema al sistema a l\'hora d\'iniciar sessió',
      'NO_VIDEOS_AUN': 'Encara no n\'hi ha vídeos grabats al sistema',
      'BOTH_PWD_EQ': 'Les dues contrasenyes han de ser les mateixes',
      'CONF_MAIL': 'Email de confirmació'

};
