export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
  'PROYECTO': 'Proyecto Carretillas',
  'ATENTICADO': "Has autenticado como ",
  'NO_VIDEOS' : 'No existen vídeos con esos parámetros.',
  'SALIR': "Salir ",
  'CAPTURA': "Captura de pantalla del vídeo",
  'DESCARGA': "Descargar en escritorio: ",
  'DESCARGA2': "Descarga",
  'EMAIL_ENTER': "Introduce tu nombre de usuario: ",
  'PWD_ENTER': "Introduce la contraseña",
  'ACCEDE': "Accede",
  'VIDEO_PEDIDO': 'Vídeo pedido',
  'PULSA_IZQ': 'Pulsa para ir a la izquierda',
  'PULSA_DER': 'Pulsa para ir a la derecha',
  'FRAME_BACK': 'Pulsa para ir a un frame anterior',
  'FRAME_POST': 'Pulsa para ir a un frame posterior',
  'VELOCIDAD': 'Velocidad',
  'FOTO': 'Toma una foto del vídeo',
  'CROP': 'Recorta el vídeo',
  'HORA_INICIO': 'Hora de inicio',
  'HORA_FIN': 'Hora de fin',
  'CLIENTE': 'Cliente',
  'PEDIDO': 'Pedido',
  'CARRETILLA': 'Carretilla',
  'NSERIE': 'Número de serie',
  'BUSCA': 'Buscar vídeos',
  'LIVE_CAMERAS': 'Camaras en directo',
  'FECHA': 'Fecha',
  'SEL_L_PEDIDO': 'Selecciona una linea de pedido',
  'L_PEDIDO': 'Linea de pedido',
  'ES': 'Español',
  'EN': 'Inglés',
  'CAT': 'Catalán',
  'ACCESS_VIDEO': 'Clica para acceder al vídeo',
  'VOLVER_VIDEO': 'Volver al vídeo completo',
  'video_completo': 'Vídeo completo',
  'linea_pedido': 'Linea de pedido',
  'INICIO': 'Inicio: ',
  'HORA': 'hora: ',
  'PULSACION': 'Pulsación: ',
  'FINAL': 'Final de ',
  'Y_PULS': ' y pulsación',
  'BAD_LOG': 'Credenciales erroneos',
  'SEL_LENG': 'Selecciona una lengua',
  'AUT_PB': 'Autentícate para acceder a la plataforma',
  'GESTION': 'Gestión',
  'ADMINISTRACION': 'Administración',
  'PWD_CH_OPT': 'Cambia la contraseña',
  'INTRO_PWD': 'Inserta una contraseña de mas de 8 dígitos, con almenos una minúscula, una mayuscula, y un número',
  'INTRO_NEW_PWD': 'Introduce una nueva contraseña',
  'INTRO_OLD_PWD': 'Introduce tu actual contraseña',
  'CHANGE_PWD': 'Cambiar contraseña',
  'OLD_PWD_REQ': 'Se requiere la contraseña actual',
  'NEW_PWD_REQ': 'Se requiere la nueva contraseña',
  'YES': 'Si',
  'USERNAME': 'Nombre de usuario: ',
  'ENT_VALID_PWD': 'Introduce una contraseña válida',
  'SEG_CH_PWD': '¿Seguro que quieres cambiarte la contraseña?',
  'ALTA_USERS': 'Registrar usuarios',
  'CLIENT': 'Cliente',
  'W_USER': 'Usuario trabajador',
  'INTRO_VALID_EM': 'Introduce un email válido',
  'EM_REQ': 'Se requiere el email',
  'DAR_ALTA': 'Dar de alta usuarios',
  'ADMIN_USERS': 'Administrar usuarios',
  'VISUALIZE': 'Visualizar',
  'DEL_USER': 'Borrar usuario',
  'SEG_DEL_USER': '¿Seguro que quieres borrar ese usuario?',
  'BUSC_USER': 'Buscar usuario',
  'SEG_ALTA_USER': '¿Seguro que quieres crear un nuevo usuario?',
  'DESC_VIDEO': 'Descargar vídeo',
  'ERR_SYS_LOG': 'Hubo un problema en el sistema al intentar autenticarse',
  'NO_VIDEOS_AUN': 'Todabía no hay vídeos grabados en el sistema',
  'BOTH_PWD_EQ': 'Ambas contraseñas nuevas deben ser igual',
  'CONF_MAIL': 'Email de confirmación'
};
