"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_EN_NAME = 'en';
exports.LANG_EN_TRANS = {
    'PROYECTO': 'Project Forklifts',
    "ATENTICADO": "You've logged in as ",
    'NO_VIDEOS': 'No videos found with that parameters',
    "SALIR": "Log out ",
    "CAPTURA": "Video screenshot",
    "DESCARGA": "Download in desktop: ",
    "DESCARGA2": "Download",
    "EMAIL_ENTER": "Type the email: ",
    "PWD_ENTER": "Type the password: ",
    "ACCEDE": "Access",
    'VIDEO_PEDIDO': 'Order video',
    'PULSA_IZQ': 'Click for going to the left',
    'PULSA_DER': 'Click for going to the right',
    'FRAME_BACK': 'Click for going to the previous frame',
    'FRAME_POST': 'Click for going to the next frame',
    'VELOCIDAD': 'Speed',
    'FOTO': 'Take a screenshot',
    'CROP': 'Crop the video',
    'HORA_INICIO': 'Beginning time',
    'HORA_FIN': 'Ending time',
    'CLIENTE': 'Costumer',
    'PEDIDO': 'Order',
    'CARRETILLA': 'Forklift',
    'NSERIE': 'Serial number',
    'BUSCA': 'Search videos',
    'LIVE_CAMERAS': 'Live cameras',
    'FECHA': 'Date',
    'SEL_L_PEDIDO': 'Select an order row',
    'L_PEDIDO': 'Order row',
    'ES': 'Spanish',
    'EN': 'English',
    'CAT': 'Catalan',
    'ACCESS_VIDEO': 'Click for accessing the video',
    'VOLVER_VIDEO': 'Return to the full video',
    'video_completo': 'Full video',
    'linea_pedido': 'Order row',
    'INICIO': 'Start ',
    'HORA': 'time ',
    'PULSACION': 'Tab ',
    'FINAL': 'Ending of ',
    'Y_PULS': ' and tab',
    'BAD_LOG': 'Bad Credentials',
    'SEL_LENG': 'Select a language',
    'AUT_PB': 'Autenticate to access the platform',
    'GESTION': 'Management',
    'ADMINISTRACION': 'Administration'
};
