export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'PROYECTO': 'Project Forklifts',
    "ATENTICADO": "You've logged in as ",
    'NO_VIDEOS' : 'No videos found with that parameters',
    "SALIR": "Log out ",
    "CAPTURA": "Video screenshot",
    "DESCARGA": "Download in desktop: ",
    "DESCARGA2": "Download",
    "EMAIL_ENTER": "Type the username: ",
    "PWD_ENTER": "Type the password: ",
    "ACCEDE": "Access",
    'VIDEO_PEDIDO': 'Order video',
    'PULSA_IZQ': 'Click for going to the left',
    'PULSA_DER': 'Click for going to the right',
    'FRAME_BACK': 'Click for going to the previous frame',
    'FRAME_POST': 'Click for going to the next frame',
    'VELOCIDAD': 'Speed',
    'FOTO': 'Take a screenshot',
    'CROP': 'Crop the video',
    'HORA_INICIO': 'Beginning time',
    'HORA_FIN': 'Ending time',
    'CLIENTE': 'Costumer',
    'PEDIDO': 'Order',
    'CARRETILLA': 'Forklift',
    'NSERIE': 'Serial number',
    'BUSCA': 'Search videos',
    'LIVE_CAMERAS': 'Live cameras',
    'FECHA': 'Date',
    'SEL_L_PEDIDO': 'Select an order row',
    'L_PEDIDO': 'Order row',
    'ES': 'Spanish',
    'EN': 'English',
    'CAT': 'Catalan',
    'ACCESS_VIDEO': 'Click for accessing the video',
    'VOLVER_VIDEO': 'Return to the full video',
    'video_completo': 'Full video',
    'linea_pedido': 'Order row',
    'INICIO': 'Start ',
    'HORA': 'time ',
    'PULSACION': 'Tab ',
    'FINAL': 'Ending of ',
    'Y_PULS': ' and tab',
    'BAD_LOG': 'Bad Credentials',
    'SEL_LENG': 'Select a language',
    'AUT_PB': 'Autenticate to access the platform',
    'GESTION': 'Management',
    'ADMINISTRACION': 'Administration',
    'PWD_CH_OPT': 'Change your password',
    'INTRO_PWD': 'Type a password more than 8 digits, with at least one lowercase digit, one uppercase digit and one number',
    'INTRO_NEW_PWD': 'Type the new password',
    'INTRO_OLD_PWD': 'Type your current password',
    'CHANGE_PWD': 'Change the password',
    'OLD_PWD_REQ': 'Current password is required',
    'NEW_PWD_REQ': 'New password is required',
    'YES': 'Yes',
    'USERNAME': 'Username: ',
    'ENT_VALID_PWD': 'Enter a valid password',
    'SEG_CH_PWD': 'Are you sure you want to change your password?',
    'ALTA_USERS': 'Register users',
    'CLIENT': 'Client',
    'W_USER': 'Worker user',
    'INTRO_VALID_EM': 'Enter a valid email',
    'EM_REQ': 'The email is required',
    'DAR_ALTA': 'Register an user',
    'ADMIN_USERS': 'Manage users',
    'VISUALIZE': 'Visualize',
    'DEL_USER': 'Remove an user',
    'SEG_DEL_USER': 'Are you sure you want to delete that user?',
    'BUSC_USER': 'Search users',
    'SEG_ALTA_USER': 'Are you sure you want to create a new user?',
    'DESC_VIDEO': 'Download video',
    'ERR_SYS_LOG': 'There was a problem in the system while log in',
    'NO_VIDEOS_AUN': 'No videos recorded yet',
    'BOTH_PWD_EQ': 'Both new passwords must be equal',
    'CONF_MAIL': 'Confirmation email'
};
