"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_CAT_NAME = 'cat';
exports.LANG_CAT_TRANS = {
    "PROYECTO": "Projecte Carretons",
    "ATENTICADO": "T'has authenticat com a ",
    "SALIR": "Eixir ",
    'NO_VIDEOS': 'No n\'hi ha videos amb els paràmetres buscats',
    "CAPTURA": "Captura de la pantalla del video",
    "DESCARGA": "Descarrega a l'escriptori",
    "DESCARGA2": "Descarrega",
    "EMAIL_ENTER": "Introduix l'email: ",
    "PWD_ENTER": "Introduix la contrasenya: ",
    "ACCEDE": "Accedix",
    'VIDEO_PEDIDO': 'Video comanda',
    'PULSA_IZQ': 'Pulsa per anar a l\'esquerra',
    'PULSA_DER': 'Pulsa per anar a la dreta',
    'FRAME_BACK': 'Pulsa per anar un frame anterior',
    'FRAME_POST': 'Pulsa per anar un frame posterior',
    'VELOCIDAD': 'Velocitat',
    'FOTO': 'Pren una foto del video',
    'CROP': 'Retalla el video',
    'HORA_INICIO': 'Hora d\'inici',
    'HORA_FIN': 'Hora de final',
    'CLIENTE': 'Client',
    'PEDIDO': 'Comanda',
    'CARRETILLA': 'Carretó',
    'NSERIE': 'Nombre de sèrie',
    'BUSCA': 'Cerca videos',
    'LIVE_CAMERAS': 'Càmeres en directe',
    'FECHA': 'Data',
    'SEL_L_PEDIDO': 'Selecciona una línea de comanda',
    'L_PEDIDO': 'Línea de comanda',
    'ES': 'Espanyol',
    'EN': 'Anglès',
    'CAT': 'Català',
    'ACCESS_VIDEO': 'Clicka per accedir el vídeo',
    'VOLVER_VIDEO': 'Tornar al video sencer',
    'video_completo': 'Video sencer',
    'linea_pedido': 'Línea de comanda',
    'INICIO': 'Inici: ',
    'HORA': 'hora ',
    'PULSACION': 'Pulsació ',
    'FINAL': 'Final de ',
    'Y_PULS': ' i pulsació',
    'BAD_LOG': 'Credencials erronis',
    'SEL_LENG': 'Selecciona una llengua',
    'AUT_PB': 'Autentica\'t per accedir el web',
    'GESTION': 'Gestió',
    'ADMINISTRACION': 'Administració'
};
